// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdh--8zC8udvpN_bar-z9csSPo-AaajSQ',
    appId: '1:473266082225:web:9bd754595bc9b8652b6d90',
    messagingSenderId: '473266082225',
    projectId: 'hero-games-case-431ba',
    authDomain: 'hero-games-case-431ba.firebaseapp.com',
    storageBucket: 'hero-games-case-431ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5ajoXei703xm_xy_0joMvR11G7wi6fc',
    appId: '1:473266082225:android:d1a39654ccbff5932b6d90',
    messagingSenderId: '473266082225',
    projectId: 'hero-games-case-431ba',
    storageBucket: 'hero-games-case-431ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbFFb5Xy3DY4qOlw_PebYe9Zkpyk4jXk',
    appId: '1:473266082225:ios:a54f0718c2c02bf92b6d90',
    messagingSenderId: '473266082225',
    projectId: 'hero-games-case-431ba',
    storageBucket: 'hero-games-case-431ba.appspot.com',
    iosBundleId: 'com.example.heroGamesCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVbFFb5Xy3DY4qOlw_PebYe9Zkpyk4jXk',
    appId: '1:473266082225:ios:14f656213d34dcee2b6d90',
    messagingSenderId: '473266082225',
    projectId: 'hero-games-case-431ba',
    storageBucket: 'hero-games-case-431ba.appspot.com',
    iosBundleId: 'com.example.heroGamesCase.RunnerTests',
  );
}
